### PR TITLE
Try to fix spontanous QA tests failures.

### PR DESCRIPTION
**Pull request by majioa**

### CODE REVIEW

**Comment by dmcnulla** [comment]
I see the changes. I have no objections to them. The result does not appear to be more reliable.

**Comment by majioa** [comment]
Yes, I'll think about it...

**Comment by majioa** [comment]
@dmcnulla  I hope i fixed it... but it seems that coveralls will show worse result since I added the code and not added tests

**Comment by dmcnulla** [comment]
I don't believe the small decrease is much to worry about. Do we need more tests? The coverage percentage seems low already. I suppose most of the non-coverage are error cases that are more difficult to create. That should be a future consideration, but not something to hold up the PR.

**Comment by dmcnulla** [comment]
https://coveralls.io/builds/5740472/source?filename=lib%2Fntp%2Fserver%2Fbase.rb
Upon reviewing the coverage, I do not believe it is accurate. There is no way the initialize method body lines are not getting run. I will investigate the coverage report issue with coveralls & sinplecov.

Update: The error happens with codeclimate coverage, and with simplecov itself. I have submitted an [issue with simplecov](https://github.com/colszowka/simplecov/issues/489).

**Comment by majioa** [comment]
> not something to hold up the PR.

So if no stoppers are presented for the PR, merge it, since do a merge procedure should do a non-author =)

**Comment by dmcnulla** [comment]
An author is somebody who writes stuff. Since you are writing, and authorized, I assumed you could merge, too.

**Comment by dmcnulla** [comment]
BTW, It seems much more stable to me.

**Comment by majioa** [comment]
@dmcnulla  I meant an author of a patch

**Pull request merged**
